# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19b46c2440dae80d5dbc3a10ca54a3378cbf982e50c499cfe75def5ddabc3e2c4267097a7debce7a671b9925e3016df887ad524674ce689a62e35375f9c23764

test:
  secret_key_base: 5db48906405e386122d5dce3f8113f409d67e671217ead7df3e200db247e48d594db52e08ccfec1c9614af40d99fca95c544c0c62719f8ad1454e545ca644d5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
